### ISSUE TITLE
Fix ranger in Fedora

### ISSUE THREAD

**Issue by abitrolly** [yakshaveinc/linux#8]
Shaving Yak for @techtonik who wants to see his fix https://github.com/ranger/ranger/issues/935 available on his Fedora workstation, but:
 * [x] Fedora 28 [ships version 1.7.2](https://koji.fedoraproject.org/koji/packageinfo?packageID=10725) (fixed in [fedora#1408563](https://bugzilla.redhat.com/show_bug.cgi?id=1408563))
   * [x] Last [update in Bodhi](https://bodhi.fedoraproject.org/updates/?packages=ranger) is 1.6.1 (fixed by [filiperosset](https://bodhi.fedoraproject.org/users/filiperosset))
     * [x] [Release monitoring](https://release-monitoring.org/project/7426) is broken (fixed)
---

[ranger](https://ranger.github.io/) version in Fedora is outdated, because upstream URL is changed. 

![image](https://user-images.githubusercontent.com/8781107/40031483-940eff96-57f8-11e8-9753-165187fa0957.png)

Fixing this will make release-monitoring system aware of new versions and let other people close the widening gap.

---

### Quest: Update $package in Fedora

* [x] Find up-to-date software website and latest software version
* [x] Find $package for the software in [release monitoring](https://release-monitoring.org/)
* [x] Check that release-monitoring show latest version
* [x] Check that release-monitoring created bugzilla issue about latest version
* [ ] ~Create build for Bodhi in testing-updates repository~ (done by [filiperosset](https://bodhi.fedoraproject.org/users/filiperosset))
* [ ] ~Talk with people to release newer version~ (done by [filiperosset](https://bodhi.fedoraproject.org/users/filiperosset))

**Comment by abitrolly** [comment]
Release monitoring created bug for the latest version - https://apps.fedoraproject.org/datagrepper/raw?package=ranger

**Comment by abitrolly** [comment]
Can not get to Fedora package source - https://github.com/fedora-infra/fedora-packages/issues/364 - without it it looks there is nothing one can do.

**Comment by uinput** [comment]
@abitrolly Are you looking for the spec file? [There](https://src.fedoraproject.org/rpms/ranger/tree/) you go. Obviously, there exists a pull request for updating already.

**Comment by abitrolly** [comment]
@uinput now that there is [the patch](https://src.fedoraproject.org/rpms/ranger/pull-request/1) and [the bug](https://bugzilla.redhat.com/show_bug.cgi?id=1592733) how to move this forward?

**Comment by uinput** [comment]
@abitrolly Have you tried to contact the maintainer on any other way than the bug tracker? [Here](https://fedoraproject.org/wiki/Package_maintainer_policy#What_to_do_if_a_maintainer_is_absent)'s the procedure in case maintainers do not respond.

**Comment by abitrolly** [comment]
It is done - https://bugzilla.redhat.com/show_bug.cgi?id=1408563#c16
